### ISSUE TITLE
Remove .idea folder from git

### ISSUE THREAD

**Issue by theshaunwalker** [EmaSerra/FRS#3]
The .idea folder is the PHPStorm workspace settings, so you should never add it to git.
So you should either add it to your .gitignore in the repository, or you can add it to gits global .gitignore so it will be ignored no matter which repository you're working with.

**Comment by theshaunwalker** [comment]
FYI I do have a PR open #1 ;)

**Comment by EmaSerra** [comment]
folder .idea removed
